---
sidebar: sidebar 
permalink: reference_integration_faq.html 
keywords: faq, questions, integration, migration, cloud manager, cloud central, authentication, users, accounts, email, ldap, scripts, automation 
summary: Cloud Manager 3.5로 업그레이드할 때 NetApp은 NetApp Cloud Central과 통합할 특정 Cloud Manager 시스템을 선택하지 않을 경우 선택합니다. 이 FAQ는 프로세스에 관한 질문에 답할 수 있습니다. 
translate: false 
---
= 질문과 대답: Cloud Manager와 NetApp Cloud Central의 통합
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager 3.4 이하에서 업그레이드할 때 NetApp은 NetApp Cloud Central과 통합할 특정 Cloud Manager 시스템을 아직 통합되지 않은 경우에 선택합니다. 이 FAQ는 프로세스에 관한 질문에 답할 수 있습니다.



== NetApp Cloud Central이란?

NetApp Cloud Central은 NetApp 클라우드 데이터 서비스에 액세스하고 이를 관리할 수 있는 중앙의 위치입니다. 이러한 서비스를 사용하여 클라우드에서 중요한 애플리케이션을 실행하고, 자동화된 DR 사이트를 생성하고, SaaS 데이터를 백업하고, 여러 클라우드 간에 데이터를 효과적으로 마이그레이션 및 제어할 수 있습니다.



== NetApp이 Cloud Central과 Cloud Manager 시스템을 통합하는 이유는 무엇입니까?

Cloud Manager와 NetApp Cloud Central의 통합은 간소화된 배포 경험, 여러 Cloud Manager 시스템을 보고 관리할 수 있는 단일 위치, 중앙 집중식 사용자 인증 등 여러 가지 이점을 제공합니다.



== 통합 프로세스 중에 발생하는 현상

NetApp은 Cloud Manager 시스템의 모든 로컬 사용자 계정을 Cloud Central에서 사용할 수 있는 중앙 집중식 사용자 인증으로 마이그레이션합니다.



== 중앙 집중식 사용자 인증은 어떻게 작동합니까?

중앙 집중식 사용자 인증을 통해 Cloud Manager 시스템과 Cloud Manager와 Cloud Sync 같은 다른 데이터 서비스 간에 동일한 자격 증명 세트를 사용할 수 있습니다. 또한 암호를 잊어버린 경우 쉽게 재설정할 수 있습니다.



== Cloud Central 사용자 계정에 가입해야 합니까?

NetApp은 Cloud Manager 시스템을 Cloud Central과 통합할 때 사용할 Cloud Central 사용자 계정을 생성합니다. 등록 프로세스를 완료하려면 비밀번호를 재설정하기만 하면 됩니다.



== Cloud Central 사용자 계정이 이미 있는 경우 어떻게 해야 합니까?

Cloud Manager에 로그인하는 데 사용하는 이메일 주소가 Cloud Central 사용자 계정의 이메일 주소와 일치하면 Cloud Manager 시스템에 직접 로그인할 수 있습니다.



== Cloud Manager 시스템에 여러 사용자 계정이 있는 경우 어떻게 해야 합니까?

NetApp은 모든 로컬 사용자 계정을 Cloud Central 사용자 계정으로 마이그레이션합니다. 모든 사용자는 자신의 암호를 재설정해야 합니다.



== 여러 Cloud Manager 시스템에서 동일한 이메일 주소를 사용하는 사용자 계정이 있는 경우 어떻게 해야 합니까?

암호를 한 번만 재설정하기만 하면 동일한 Cloud Central 사용자 계정을 사용하여 각 Cloud Manager 시스템에 로그인할 수 있습니다.



== 로컬 사용자 계정이 잘못된 이메일 주소를 사용하는 경우 어떻게 해야 합니까?

암호를 재설정하려면 유효한 이메일 주소가 필요합니다. Cloud Manager 인터페이스 오른쪽 아래에 있는 채팅 아이콘을 통해 문의해 주십시오.



== Cloud Manager API용 자동화 스크립트가 있는 경우 어떻게 됩니까?

모든 API는 이전 버전과 호환됩니다. 암호를 재설정할 때 암호를 변경하는 경우 암호를 사용하는 스크립트를 업데이트해야 합니다.



== Cloud Manager 시스템에서 LDAP를 사용하는 경우 어떻게 됩니까?

시스템에서 LDAP를 사용하는 경우 NetApp은 시스템을 Cloud Central과 자동으로 통합할 수 없습니다. 다음 단계를 수동으로 수행해야 합니다.

. 에서 새로운 Cloud Manager 시스템을 구축합니다 https://cloud.netapp.com/["NetApp Cloud Central에서"^].
. https://services.cloud.netapp.com/misc/federation-support["새 시스템으로 LDAP를 설정합니다"^].
. link:task_adding_ontap_cloud.html["기존 Cloud Volumes ONTAP 시스템을 검색합니다"] 을 참조하십시오.
. 이전 Cloud Manager 시스템을 삭제합니다.




== Cloud Manager 시스템을 어디에 설치해도 됩니까?

아니요 NetApp은 AWS, Azure 또는 사내 등 위치에 상관없이 Cloud Central과 시스템을 통합합니다.


NOTE: 단, AWS 상용 클라우드 서비스 환경은 예외입니다.
