---
pagenav: false 
sidebar: sidebar 
permalink: task_getting_started_azure.html 
keywords: microsoft, azure, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, marketplace, virtual machine, vnet, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, permissions, custom role, role, json, permissions, virtual machine, video, connectivity, internet, outbound, endpoint, connection, networks, vpn, replicating, policy, iam, setupasservice, sign up, cloud manager, cloud volumes ontap, cloud ontap, subscription, create 
summary: 몇 가지 간단한 단계를 완료하여 Azure에서 Cloud Volumes ONTAP를 시작할 수 있습니다. 
---
= Azure에서 Cloud Volumes ONTAP 시작하기
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure를 설정한 다음 NetApp Cloud Central에서 Cloud Manager 소프트웨어를 배포하여 Cloud Volumes ONTAP를 시작하십시오. Cloud Manager를 구축할 수 있는 별도의 지침이 제공됩니다 link:task_installing_azure_gov.html["Azure 미국 정부 지역"] 및 IN .



=== 네트워크 설정

[role="quick-margin-para"]
클라우드 관리자 및 Cloud Volumes ONTAP가 여러 엔드포인트에 연결할 수 있도록 대상 VNET에서 아웃바운드 인터넷 액세스를 활성화합니다.

[role="quick-margin-para"]
이 단계는 Cloud Manager가 아웃바운드 인터넷 액세스 없이 Cloud Volumes ONTAP를 구축할 수 없기 때문에 중요합니다. 아웃바운드 연결을 제한해야 하는 경우 의 끝점 목록을 참조하십시오 link:reference_networking_cloud_manager.html#outbound-internet-access["클라우드 관리자"] 및 .



=== 필요한 Azure 권한을 제공합니다

[role="quick-margin-para"]
NetApp Cloud Central에서 Cloud Manager를 구축할 때 Cloud Manager 가상 머신을 구축할 권한이 있는 Azure 계정을 사용해야 합니다.

. 를 다운로드합니다 https://mysupport.netapp.com/cloudontap/iampolicies["Azure를 위한 NetApp Cloud Central 정책"^].
. Azure 구독 ID를 "AssignableScopes" 필드에 추가하여 JSON 파일을 수정합니다.
. JSON 파일을 사용하여 이름이 _Azure SetupAsService_인 Azure에서 사용자 지정 역할을 생성합니다.
+
예: * az 역할 정의 create -- role-definition C:\Policy_for_Setup_as_Service_Azure.json *

. Azure 포털에서 Cloud Central에서 Cloud Manager를 배포할 사용자에게 사용자 지정 역할을 할당합니다.




=== NetApp Cloud Central에서 Cloud Manager를 실행합니다

[role="quick-margin-para"]
Cloud Volumes ONTAP를 구축 및 관리하려면 Cloud Manager 소프트웨어가 필요합니다. Cloud Manager 인스턴스를 시작하는 데는 몇 분 밖에 걸리지 않습니다 https://cloud.netapp.com["Cloud Central을 참조하십시오"^].



=== Cloud Manager를 사용하여 Cloud Volumes ONTAP를 실행합니다

[role="quick-margin-para"]
Cloud Manager가 준비되면 생성 을 클릭하고 구축할 시스템 유형을 선택한 다음 마법사의 단계를 완료합니다. 25분 후 첫 번째 Cloud Volumes ONTAP 시스템이 가동되어 실행 중이어야 합니다.

.관련 링크
* link:concept_evaluating.html["평가 중"]
* link:reference_networking_cloud_manager.html["Cloud Manager의 네트워킹 요구사항"]
* link:reference_networking_azure.html["Azure의 Cloud Volumes ONTAP에 대한 네트워킹 요구사항"]
* link:reference_security_groups_azure.html["Azure의 보안 그룹 규칙"]
* link:task_adding_azure_accounts.html["Cloud Manager에 Azure 계정 추가"]
* link:reference_permissions.html#what-cloud-manager-does-with-azure-permissions["Cloud Manager가 Azure 권한으로 수행하는 기능"]
* link:task_deploying_otc_azure.html["Azure에서 Cloud Volumes ONTAP 실행"]
* link:task_launching_azure_mktp.html["Azure 마켓플레이스에서 Cloud Manager 시작"]

