---
pagenav: false 
sidebar: sidebar 
permalink: task_getting_started_gcp.html 
keywords: google cloud platform, gcp, deploy cloud manager, launch cloud manager, create cloud manager, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, storage access key, gcp role, role, iam role, permissions, gcp permissions 
summary: GCP를 설정한 다음 NetApp Cloud Central에서 Cloud Manager 소프트웨어를 구축하여 Cloud Volumes ONTAP를 시작하십시오. 
---
= Google 클라우드 플랫폼에서 Cloud Volumes ONTAP 시작하기
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
GCP를 설정한 다음 NetApp Cloud Central에서 Cloud Manager 소프트웨어를 구축하여 Cloud Volumes ONTAP를 시작하십시오.

GCP에서 Cloud Volumes ONTAP를 구축하려면 Cloud Manager를 Google Cloud Platform에 설치해야 합니다.



=== 네트워크 설정

[role="quick-margin-para"]
Cloud Manager 및 Cloud Volumes ONTAP가 여러 엔드포인트에 연결할 수 있도록 타겟 VPC에서 아웃바운드 인터넷 액세스를 지원합니다.

[role="quick-margin-para"]
이 단계는 Cloud Manager가 아웃바운드 인터넷 액세스 없이 Cloud Volumes ONTAP를 구축할 수 없기 때문에 중요합니다. 아웃바운드 연결을 제한해야 하는 경우 의 끝점 목록을 참조하십시오 link:reference_networking_cloud_manager.html#outbound-internet-access["클라우드 관리자"] 및 .



=== GCP 권한 및 프로젝트 설정

[role="quick-margin-para"]
두 가지 권한 집합이 있는지 확인합니다.

. NetApp Cloud Central에서 Cloud Manager를 배포하는 GCP 사용자에게 의 권한이 있는지 확인합니다 https://occm-sample-policies.s3.amazonaws.com/Setup_As_Service_3.7.3_GCP.yaml["GCP에 대한 Cloud Central 정책"^].
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["YAML 파일을 사용하여 맞춤형 역할을 생성할 수 있습니다"^] 그런 다음 사용자에게 연결합니다. gcloud 명령줄을 사용하여 역할을 생성해야 합니다.

. Cloud Manager에서 프로젝트에서 Cloud Volumes ONTAP 시스템을 만들고 관리하는 데 필요한 권한이 있는 서비스 계정을 설정합니다.
+
6단계에서 이 서비스 계정을 Cloud Manager VM과 연결합니다.

+
** https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["GCP에서 역할을 생성합니다"^] 여기에는 에 정의된 권한이 포함됩니다. gcloud 명령줄을 사용해야 합니다.
+
이 YAML 파일에 포함된 사용 권한은 2a단계의 사용 권한과 다릅니다.

** https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["GCP 서비스 계정을 생성하고 방금 생성한 사용자 지정 역할을 적용합니다"^].
** 다른 프로젝트에 Cloud Volumes ONTAP를 배포하려는 경우 https://cloud.google.com/iam/docs/granting-changing-revoking-access#granting-console["Cloud Manager 역할을 가진 서비스 계정을 해당 프로젝트에 추가하여 액세스 권한을 부여합니다"^]. 각 프로젝트에 대해 이 단계를 반복해야 합니다.






=== 데이터 계층화에 GCP를 설정합니다

[role="quick-margin-para"]
Cloud Volumes ONTAP 9.7에서 저렴한 오브젝트 스토리지(Google 클라우드 스토리지 버킷)로 콜드 데이터를 계층화하려면 다음 두 가지 요구사항을 충족해야 합니다.

. https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["서비스 계정을 생성합니다"^] 사전 정의된 스토리지 관리 역할과 Cloud Manager 서비스 계정이 있는 사용자입니다.
+
Cloud Volumes ONTAP 작업 환경을 생성할 때 나중에 이 서비스 계정을 선택해야 합니다. 이 서비스 계정은 2단계에서 만든 서비스 계정과 다릅니다.

. https://cloud.google.com/vpc/docs/configure-private-google-access["개인 Google 액세스를 위한 Cloud Volumes ONTAP 서브넷을 구성합니다"^].


[role="quick-margin-para"]
Cloud Volumes ONTAP 9.6과 함께 데이터 계층화를 사용하려면 link:task_adding_gcp_accounts.html["그런 다음 다음 다음 단계를 수행합니다"].



=== Google Cloud API를 활성화합니다

[role="quick-margin-para"]
https://cloud.google.com/apis/docs/getting-started#enabling_apis["프로젝트에서 다음 Google Cloud API를 활성화합니다"^]. 이러한 API는 Cloud Manager 및 Cloud Volumes ONTAP를 구축하는 데 필요합니다.

* Cloud Deployment Manager V2 API
* Cloud Resource Manager API를 참조하십시오
* 컴퓨팅 엔진 API
* Stackdriver 로깅 API




=== GCP Marketplace에서 구독하십시오

[role="quick-margin-para"]
https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager["GCP Marketplace에서 Cloud Volumes ONTAP를 구독하십시오"^] 무료 평가판이 종료된 후에도 서비스가 중단되지 않도록 합니다. 생성하는 모든 Cloud Volumes ONTAP PAYGO 시스템에 대해 이 구독 요금제로 요금이 부과됩니다.



=== NetApp Cloud Central에서 Cloud Manager를 실행합니다

[role="quick-margin-para"]
Cloud Volumes ONTAP를 구축 및 관리하려면 Cloud Manager 소프트웨어가 필요합니다. GCP에서 Cloud Manager 인스턴스를 시작하는 데 몇 분 밖에 걸리지 않습니다 https://cloud.netapp.com["Cloud Central을 참조하십시오"^].

[role="quick-margin-para"]
클라우드 공급자로 GCP를 선택하면 Google에서 계정에 로그인하고 권한을 부여하라는 메시지가 표시됩니다. "허용"을 클릭하면 Cloud Manager를 배포하는 데 필요한 컴퓨팅 API에 대한 액세스 권한이 부여됩니다.



=== Cloud Manager를 사용하여 Cloud Volumes ONTAP를 실행합니다

[role="quick-margin-para"]
Cloud Manager가 준비되면 생성 을 클릭하고 구축할 시스템 유형을 선택한 다음 마법사의 단계를 완료합니다. 25분 후 첫 번째 Cloud Volumes ONTAP 시스템이 가동되어 실행 중이어야 합니다.

.관련 링크
* link:concept_evaluating.html["평가 중"]
* link:reference_networking_cloud_manager.html["Cloud Manager의 네트워킹 요구사항"]
* link:reference_networking_gcp.html["GCP의 Cloud Volumes ONTAP에 대한 네트워킹 요구 사항"]
* link:reference_firewall_rules_gcp.html["GCP의 방화벽 규칙"]
* link:reference_permissions.html#what-cloud-manager-does-with-gcp-permissions["Cloud Manager에서 GCP 권한으로 수행하는 권한입니다"]
* link:task_deploying_gcp.html["GCP에서 Cloud Volumes ONTAP를 시작합니다"]
* link:task_installing_linux.html["Linux 호스트에서 Cloud Manager 소프트웨어 다운로드 및 설치"]

